export interface Work {
    id: string,
    clientName: string,
    furnitureType: string,
    furnitureColor: string,
    woodType: string,
    price: number,
    deadline: string,
    location: string,
    type: string,
    elevator: string,
    doors: string,
    walls: string,
    pipes: string,
    wiring: string,
    plinth: boolean,
    bench:  boolean,
    plugs: boolean,
    corbel: boolean,
    picture: string,
    notes: string
}
